services:
  zap:
    image: ghcr.io/zaproxy/zaproxy:stable
    container_name: zap
    command: >
      zap.sh -daemon -host 0.0.0.0 -port 8080
      -config api.disablekey=true
      -config api.addrs.addr.name=.*
      -config api.addrs.addr.regex=true
      -addoninstall openapi
    ports:
      - "8080:8080"
    networks:
      - vuln-net
    environment:
      - ZAP_API_URL=http://zap:8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s

  nikto:
    build:
      context: ./nikto
      dockerfile: Dockerfile
    container_name: nikto
    volumes:
      - ./nikto/relatorios:/app/relatorios
    ports:
      - "5000:5000"
    networks:
      - vuln-net
    environment:
      - FLASK_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    volumes:
      - ./ui:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run dev:edge
    networks:
      - vuln-net
    environment:
      - NIKTO_SERVICE_URL=http://nikto:5000
      - ZAP_API_URL=http://zap:8080
    depends_on:
      nikto:
        condition: service_healthy
      zap:
        condition: service_healthy

networks:
  vuln-net:
    driver: bridge